name: 'Initiate Env'
description: 'Initiate the environment by generating local project stack envs'
inputs:
  domain-name:
    description: 'Domain Name: e.g jamesmiller.blog'
    required: true
  project-name:
    description: 'Project Name: e.g blog'
    required: true
  ready-player-me-subdomain:
    description: 'Subdomain used for readyplayer me'
    required: true
  aws-region:
    description: 'AWS Region: e.g us-east-1'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Deploy
      run: npm run cd:initEnvCli ${{ inputs.domain-name }} ${{ inputs.project-name }} ${{ inputs.aws-region }} ${{ inputs.ready-player-me-subdomain }}