name: 'Deploy Client Resources'
description: 'Deploy all client resources'
inputs:
  stack:
    description: 'Stack Name: e.g dev'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Deploy Client Infrastructure
    shell: bash
    run: npm run deploy:client