encryptionsalt: v1:DHb/GPoPAW0=:v1:7FX3gkfRcGXtGgUt:9ka42iCXGHNdFcMgh6vEaT0U0H1vMQ==
config:
  aws:region: eu-west-2
  test-2-shared:projectSharedResources: test-2-shared
  test-2-shared:region: eu-west-2
  test-2-shared:targetDomain: test.newpilot.app
