name: 'Deploy Server Resources'
description: 'Deploy all server resources'
inputs:
  stack:
    description: 'Stack Name: e.g dev'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Deploy Server Infrastructure
    shell: bash
    run: npm run deploy:server