name: 'Deploy'
description: 'Initiate the environment by generating local project stack envs'
inputs:
  stack:
    description: 'Stack Name: e.g dev'
    required: true
  domain-name:
    description: 'Domain Name: e.g jamesmiller.blog'
    required: true
  project-name:
    description: 'Project Name: e.g blog'
    required: true
  ready-player-me-subdomain:
    description: 'Subdomain used for readyplayer me'
    required: true
  aws-region:
    description: 'AWS Region: e.g us-east-1'
    required: true
  pulumi-config-passphrase:
    description: 'Passphrase for Pulumi'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Pulumi
      shell: bash
      run: |
        echo "Setting PULUMI_CONFIG_PASSPHRASE..."
        export PULUMI_CONFIG_PASSPHRASE=${{ inputs.pulumi-config-passphrase }}
        echo "PULUMI_CONFIG_PASSPHRASE=$PULUMI_CONFIG_PASSPHRASE" >> $GITHUB_ENV

    - name: Initialise Environment
      shell: bash
      run: npm run cd:initEnvCli ${{ inputs.domain-name }} ${{ inputs.project-name }} ${{ inputs.aws-region }} ${{ inputs.ready-player-me-subdomain }}



  # Rename this file to Initialise Environment
  # Fill out this 