name: 'Deploy Shared Resources'
description: 'Deploy all shared resources'
inputs:
  stack:
    description: 'Stack Name: e.g dev'
    required: true

runs:
  using: 'composite'
  steps:
  - name: Deploy Shared Infrastructure
    shell: bash
    run: yarn deploy:shared
  - name: Generate Client and Server Envs
    shell: bash
    run: yarn cd:generateEnvs ${{ inputs.stack }} true
