name: 'Deploy Environment'
description: 'Deploy the environment'
inputs:
  stack:
    description: 'Stack Name: e.g dev'
    required: true
  domain-name:
    description: 'Domain Name: e.g jamesmiller.blog'
    required: true
  # ready-player-me-subdomain:
  #   description: 'Subdomain used for readyplayer me'
  #   required: true
  # project-name:
  #   description: 'Project Name: e.g blog'
  #   required: true
  # aws-region:
  #   description: 'AWS Region: e.g us-east-1'
  #   required: true
  # aws-access-key-id:
  #   description: 'AWS Access Key ID'
  #   required: true
  # aws-secret-access-key:
  #   description: 'AWS Secret Access Key'
  #   required: true


runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy
      run:   npm run deploy:all:target-env ${{ inputs.stack }} ${{ inputs.domain-name }} ${{ vars.READY_PLAYER_ME_SUBDOMAIN }} ${{ vars.PROJECT_NAME }} ${{ secrets.AWS_REGION }}