name: 'Destroy Environment'
description: 'Destroy the environment'
inputs:
  stack:
    description: 'Stack Name: e.g dev'
    required: true
  project-name:
    description: 'Project Name: e.g blog'
    required: true
  aws-region:
    description: 'AWS Region: e.g us-east-1'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Pre-Destroy
      run:   npm run deploy:all:target-env ${{ inputs.stack }} ${{ inputs.domain-name }} ${{ inputs.ready-player-me-subdomain }} ${{ inputs.project-name }} ${{ inputs.aws-region }}

    - name: Destroy
      run:   npm run deploy:all:target-env ${{ inputs.stack }} ${{ inputs.domain-name }} ${{ inputs.ready-player-me-subdomain }} ${{ inputs.project-name }} ${{ inputs.aws-region }}