name: 'Initialise Environment'
description: 'Initiate the environment by generating local project stack envs'
inputs:
  stack:
    description: 'Stack Name: e.g dev'
    required: true
  domain-name:
    description: 'Domain Name: e.g jamesmiller.blog'
    required: true
  project-name:
    description: 'Project Name: e.g blog'
    required: true
  ready-player-me-subdomain:
    description: 'Subdomain used for readyplayer me'
    required: true
  aws-region:
    description: 'AWS Region: e.g us-east-1'
    required: true
  pulumi-config-passphrase:
    description: 'Passphrase for Pulumi'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Initialise Environment
      shell: bash
      run: |
        export PULUMI_CONFIG_PASSPHRASE=${{ inputs.pulumi-config-passphrase }}
        echo "PULUMI_CONFIG_PASSPHRASE=$PULUMI_CONFIG_PASSPHRASE" >> $GITHUB_ENV
        npm run cd:initEnvCli ${{ inputs.domain-name }} ${{ inputs.ready-player-me-subdomain }} ${{ inputs.project-name }} ${{ inputs.aws-region }}
    - name: Setup S3 State Buckets
      shell: bash
      run: npm run cd:s3StateBucketsSetup
  - name: Init Pulumi
      shell: bash
      run: npm run cd:initPulumi ${{ stack }}
  - name: Create Secrets
      shell: bash
      run: npm run cd:createSecrets
  - name: Generate Shared Envs
      shell: bash
      run: npm run cd:cd:generateEnvs ${{ stack }}
  - name: Deploy Shared Infrastructure
      shell: bash
      run: npm run deploy:shared