import { Metadata } from "next"
import { Container } from "./components/Global"

export const metadata: Metadata = {
  title: 'WebXR Template',
  description: 'Generated by Wrapper.js'
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Container>
          {children}
        </Container>
      </body>
    </html>
  )
}